// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package grpc;

public interface SampleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.SampleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
