// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package grpc;

public interface SampleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.SampleResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 message = 1;</code>
   * @return The message.
   */
  int getMessage();
}
