// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package grpc;

public final class SampleProto {
  private SampleProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_SampleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_SampleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_SampleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_SampleResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014sample.proto\022\004grpc\"\033\n\rSampleRequest\022\n\n" +
      "\002id\030\001 \001(\005\"!\n\016SampleResponse\022\017\n\007message\030\001" +
      " \001(\0052@\n\013SendService\0221\n\004Send\022\023.grpc.Sampl" +
      "eRequest\032\024.grpc.SampleResponseB\025\n\004grpcB\013" +
      "SampleProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_grpc_SampleRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_SampleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_SampleRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_grpc_SampleResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_SampleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_SampleResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
